// Generated by Dagger (https://dagger.dev).
package com.titaniel.zerobasedbudgetingapp.fragments.fragment_budget.fragment_update_budget;

import androidx.lifecycle.SavedStateHandle;
import com.titaniel.zerobasedbudgetingapp.database.repositories.BudgetRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class UpdateBudgetViewModel_Factory implements Factory<UpdateBudgetViewModel> {
  private final Provider<SavedStateHandle> savedStateHandleProvider;

  private final Provider<BudgetRepository> budgetRepositoryProvider;

  public UpdateBudgetViewModel_Factory(Provider<SavedStateHandle> savedStateHandleProvider,
      Provider<BudgetRepository> budgetRepositoryProvider) {
    this.savedStateHandleProvider = savedStateHandleProvider;
    this.budgetRepositoryProvider = budgetRepositoryProvider;
  }

  @Override
  public UpdateBudgetViewModel get() {
    return newInstance(savedStateHandleProvider.get(), budgetRepositoryProvider.get());
  }

  public static UpdateBudgetViewModel_Factory create(
      Provider<SavedStateHandle> savedStateHandleProvider,
      Provider<BudgetRepository> budgetRepositoryProvider) {
    return new UpdateBudgetViewModel_Factory(savedStateHandleProvider, budgetRepositoryProvider);
  }

  public static UpdateBudgetViewModel newInstance(SavedStateHandle savedStateHandle,
      BudgetRepository budgetRepository) {
    return new UpdateBudgetViewModel(savedStateHandle, budgetRepository);
  }
}
