// Generated by Dagger (https://dagger.dev).
package com.titaniel.zerobasedbudgetingapp.fragments.fragment_budget.fragment_update_budget;

import dagger.internal.Factory;
import dagger.internal.Preconditions;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class UpdateBudgetViewModel_HiltModules_KeyModule_ProvideFactory implements Factory<String> {
  @Override
  public String get() {
    return provide();
  }

  public static UpdateBudgetViewModel_HiltModules_KeyModule_ProvideFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static String provide() {
    return Preconditions.checkNotNullFromProvides(UpdateBudgetViewModel_HiltModules.KeyModule.provide());
  }

  private static final class InstanceHolder {
    private static final UpdateBudgetViewModel_HiltModules_KeyModule_ProvideFactory INSTANCE = new UpdateBudgetViewModel_HiltModules_KeyModule_ProvideFactory();
  }
}
