// Generated by Dagger (https://dagger.dev).
package com.titaniel.zerobasedbudgetingapp.database.repositories;

import com.titaniel.zerobasedbudgetingapp.database.room.daos.BudgetDao;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class BudgetRepository_Factory implements Factory<BudgetRepository> {
  private final Provider<BudgetDao> budgetDaoProvider;

  public BudgetRepository_Factory(Provider<BudgetDao> budgetDaoProvider) {
    this.budgetDaoProvider = budgetDaoProvider;
  }

  @Override
  public BudgetRepository get() {
    return newInstance(budgetDaoProvider.get());
  }

  public static BudgetRepository_Factory create(Provider<BudgetDao> budgetDaoProvider) {
    return new BudgetRepository_Factory(budgetDaoProvider);
  }

  public static BudgetRepository newInstance(BudgetDao budgetDao) {
    return new BudgetRepository(budgetDao);
  }
}
