// Generated by Dagger (https://dagger.dev).
package com.titaniel.zerobasedbudgetingapp.database.repositories;

import com.titaniel.zerobasedbudgetingapp.database.room.daos.CategoryDao;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class CategoryRepository_Factory implements Factory<CategoryRepository> {
  private final Provider<CategoryDao> categoryDaoProvider;

  public CategoryRepository_Factory(Provider<CategoryDao> categoryDaoProvider) {
    this.categoryDaoProvider = categoryDaoProvider;
  }

  @Override
  public CategoryRepository get() {
    return newInstance(categoryDaoProvider.get());
  }

  public static CategoryRepository_Factory create(Provider<CategoryDao> categoryDaoProvider) {
    return new CategoryRepository_Factory(categoryDaoProvider);
  }

  public static CategoryRepository newInstance(CategoryDao categoryDao) {
    return new CategoryRepository(categoryDao);
  }
}
