// Generated by Dagger (https://dagger.dev).
package com.titaniel.zerobasedbudgetingapp.database.repositories;

import com.titaniel.zerobasedbudgetingapp.database.room.daos.PayeeDao;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PayeeRepository_Factory implements Factory<PayeeRepository> {
  private final Provider<PayeeDao> payeeDaoProvider;

  public PayeeRepository_Factory(Provider<PayeeDao> payeeDaoProvider) {
    this.payeeDaoProvider = payeeDaoProvider;
  }

  @Override
  public PayeeRepository get() {
    return newInstance(payeeDaoProvider.get());
  }

  public static PayeeRepository_Factory create(Provider<PayeeDao> payeeDaoProvider) {
    return new PayeeRepository_Factory(payeeDaoProvider);
  }

  public static PayeeRepository newInstance(PayeeDao payeeDao) {
    return new PayeeRepository(payeeDao);
  }
}
