// Generated by Dagger (https://dagger.dev).
package com.titaniel.zerobasedbudgetingapp.database.repositories;

import com.titaniel.zerobasedbudgetingapp.database.room.daos.TransactionDao;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class TransactionRepository_Factory implements Factory<TransactionRepository> {
  private final Provider<TransactionDao> transactionDaoProvider;

  public TransactionRepository_Factory(Provider<TransactionDao> transactionDaoProvider) {
    this.transactionDaoProvider = transactionDaoProvider;
  }

  @Override
  public TransactionRepository get() {
    return newInstance(transactionDaoProvider.get());
  }

  public static TransactionRepository_Factory create(
      Provider<TransactionDao> transactionDaoProvider) {
    return new TransactionRepository_Factory(transactionDaoProvider);
  }

  public static TransactionRepository newInstance(TransactionDao transactionDao) {
    return new TransactionRepository(transactionDao);
  }
}
