
name: CI

on:
  pull_request:
    branches: '*'

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - run: bash ./gradlew test --stacktrace

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - run: bash ./gradlew build --stacktrace
        
#  test_instrumentation:
#    name: Instrumentation Test
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v2
#
#    - uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 29
#        script: |
#          git update-index --chmod=+x gradlew
#          adb logcat -c
#          adb logcat &
#          ./gradlew connectedCheck --stacktrace
        # ./gradlew :presentation:connectedDebugAndroidTest
