
name: Gradle Test/Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

  workflow_dispatch:

jobs:
  gradle_build:
    name: Run Gradle Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      
      - name: Build
        run: bash ./gradlew build --stacktrace
  gradle_test:
    name: Run Gradle Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      
      - name: Test
        run: bash ./gradlew test --stacktrace
